# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Params-Classify
version:      0.001
version_from: lib/Params/Classify.pm
installdirs:  site
requires:
    Scalar::Util:                  1.01

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.30
