---
name: Params-Classify
version: 0.009
author:
  - 'Andrew Main (Zefram) <zefram@fysh.org>'
abstract: argument type classification
license: perl
resources:
  license: http://dev.perl.org/licenses/
requires:
  Exporter: 0
  Scalar::Util: 1.01
  parent: 0
  perl: 5.006
  strict: 0
  warnings: 0
build_requires:
  Module::Build: 0
  Test::More: 0
  perl: 5.006
  strict: 0
  warnings: 0
recommends:
  XSLoader: 0
dynamic_config: 1
provides:
  Params::Classify:
    file: lib/Params/Classify.pm
    version: 0.009
generated_by: Module::Build version 0.280801
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.2.html
  version: 1.2
distribution_type: module
